### PR TITLE
Fix MySQL resource leak.

### PR DESCRIPTION
**Pull request by jjm223**
New thread pools were being created without closing the old ones. This led to a buildup of sleeping threads, which can lead to an out of memory error and generally slow down the server it's running on.

Let me know if you'd like me to change anything, of course.

### CODE REVIEW

**Comment by jjm223** [comment]
[https://github.com/Armarr/Autorank-2/issues/154](url)

I should also add that this may be the fix to this issue.

**Comment by henrikhierl** [comment]
I still have thread pool leaks using the latest Build #522, which should include your fix.

**Comment by jjm223** [comment]
@henrikhierl Are you using MySQL storage?

I use MySQL, and it's always been working fine. However, I do use an older version with the leak fix applied over that. However, when testing the latest version, it did work fine.

**Comment by henrikhierl** [comment]
@jjm223 We are using MySQL storage, with mysql 5.7 in a bungeecord enviroment. 
Which version of Autorank you are using?

**Comment by jjm223** [comment]
@henrikhierl I found that anything after 3.7.2 did not work properly for me. That's the one we're using for now. 

Are you positive this is an Autorank issue? Does it leak on a server with only Autorank installed for you?

**Comment by henrikhierl** [comment]
@jjm223  We have tested only Autorank and Vault latest builds on the latest spigot (1.10.2)  and still had thread leaks.

**Pull request merged**
