### PR TITLE
Add support for UltimateCore 2.x (API changed)

### PR DESCRIPTION
**Pull request by Bammerbom**

### CODE REVIEW

**Comment by Staartvin** [comment]
It might be handler to merge UltimateCoreHandler and UltimateCore2Hander as they might conflict.

**Comment by Bammerbom** [comment]
Do you care if I do some reformatting?

**Comment by Bammerbom** [comment]
I am not sure if this works, didnt test this.

But at least you can try :)

**Comment by Staartvin** [comment]
I cannot seem to find any version 2.0.0, only 1.1.11. Are these the same version?

**Comment by Bammerbom** [comment]
It is not yet uploaded. It still needs some testing, but the api is done so I made the PR. 

Here is a jar so you can add it to your repo: https://www.mediafire.com/?vymc66f9s3dxivz

**Pull request merged**
